# Generated by Django 2.2.6 on 2019-10-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['room', 'drink'], 'verbose_name': 'history'},
        ),
        migrations.AlterModelOptions(
            name='stocks',
            options={'ordering': ['room', 'drink'], 'verbose_name': 'stocks'},
        ),
        migrations.AlterField(
            model_name='drinks',
            name='by_bottle',
            field=models.BooleanField(),
        ),
    ]
