# Generated by Django 2.2.7 on 2019-12-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_soldout',
            field=models.BooleanField(default=False),
        ),
    ]
