# Generated by Django 2.2.7 on 2019-11-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandefood',
            name='is_livre',
            field=models.BooleanField(default=False),
        ),
    ]
