# Generated by Django 2.2.6 on 2019-10-10 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191009_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocks',
            options={'ordering': ['room', 'drinks'], 'verbose_name': 'stocks'},
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='drink',
            new_name='drinks',
        ),
    ]
