# Generated by Django 2.2.7 on 2019-11-30 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_demandefood_is_livre'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandefood',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
