# Generated by Django 2.2.6 on 2020-01-12 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191217_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenteSum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitySum', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('drinks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.drinks')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rooms')),
            ],
            options={
                'verbose_name': 'VenteSum',
                'ordering': ['room', 'drinks'],
            },
        ),
    ]
