# Generated by Django 2.2.6 on 2019-10-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_stocks_is_accepter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serveur_salle_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucque', models.CharField(max_length=30)),
                ('fams', models.IntegerField()),
                ('is_Zi', models.BooleanField(default=False)),
            ],
            options={
                'permissions': [('can_use_salle_1', 'Can use salle 1')],
            },
        ),
    ]
