# Generated by Django 2.2.6 on 2020-01-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200112_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventesum',
            options={'ordering': ['room', 'drink', '-date'], 'verbose_name': 'VenteSum'},
        ),
    ]
