# Generated by Django 2.2.6 on 2019-10-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_serveur_salle_1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serveur_salle_1',
            options={'ordering': ['fams', 'proms'], 'permissions': [('can_use_salle_1', 'Can use salle 1')], 'verbose_name': 'Serveur de la Salle 1'},
        ),
        migrations.AddField(
            model_name='serveur_salle_1',
            name='proms',
            field=models.IntegerField(default=218),
        ),
    ]
