# Generated by Django 2.2.7 on 2019-11-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('main', '0009_group_serveur_salle_1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group_serveur_salle_1',
        ),
    ]
