# Generated by Django 2.2.7 on 2019-11-16 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_group_serveur_salle_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.drinks'),
        ),
        migrations.AlterField(
            model_name='history',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rooms'),
        ),
    ]
