# Generated by Django 2.2.7 on 2019-11-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('main', '0011_auto_20191116_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission_serveur_salle_1',
            name='permission_ptr',
        ),
        migrations.DeleteModel(
            name='Serveur_salle_1',
        ),
        migrations.AlterField(
            model_name='history',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Permission_serveur_salle_1',
        ),
    ]
